<a href="https://colab.research.google.com/github/avkornaev/Python-for-image-processing-course/blob/main/Lesson15_Numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What are arrays?

In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
c = np.array(a)
d = 2*c
print(c)
print(d)
print(c**2)

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8])
c = np.array([9,10,11,12,13])
print(a+c)

[10 12 14 16 18]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]], dtype=np.float64)
type(y)

numpy.ndarray

In [ ]:
import cv2
from skimage import io
img1 = cv2.imread('/content/1122_1.tiff')
print(type(img1))
np.size(img1)

<class 'numpy.ndarray'>


32216187

In [ ]:
e = np.ones((3,3))
f = np.zeros((3,3))
g = np.ones_like(img1)
h = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.shape(h))
print(h)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
i = h[:2, 1:3]
print(i)

[[2 3]
 [6 7]]


In [ ]:
np.sum(h,axis=0)
np.sum(h,axis=1)

array([10, 26, 42])

In [ ]:
np.max(h)

12

In [ ]:
h.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])